# Generated by Django 6.0 on 2025-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=15)),
                ('long', models.DecimalField(decimal_places=8, max_digits=15)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=100)),
                ('moves', models.JSONField()),
                ('sprite', models.URLField()),
            ],
        ),
    ]
